{
 "title": "Lab 3 — CPU, память и диск",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "CPU: накопленное время по режимам",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "node_cpu_seconds_total", "legendFormat": "CPU {{cpu}} · {{mode}}" }
   ]
  },
  {
   "title": "CPU: загрузка, %",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
     "legendFormat": "{{instance}} {{mode}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Память: занято, %",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 7, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}} {{mode}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Диск: занято, %",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 7, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - node_filesystem_avail_bytes{mountpoint=\"/var/lib/docker\"} / node_filesystem_size_bytes{mountpoint=\"/var/lib/docker\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}